# Generated by Django 3.0.2 on 2020-12-13 12:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_length', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('owner', models.CharField(max_length=50)),
                ('identity_number', models.IntegerField()),
                ('contituency', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('land_reference', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=50)),
                ('land_use', models.CharField(max_length=50)),
                ('ownership', models.CharField(max_length=50)),
                ('centroid_X', models.FloatField()),
                ('centroid_y', models.FloatField()),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
