# Generated by Django 3.0.2 on 2020-12-13 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0002_mpesapayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='mpesaTransaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plot.MpesaPayments'),
        ),
    ]
