# Generated by Django 3.0.2 on 2020-12-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0003_plot_mpesatransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='mpesaTransaction',
        ),
        migrations.AddField(
            model_name='plot',
            name='paind',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
