# Generated by Django 3.0.2 on 2020-12-13 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0004_auto_20201213_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandratesPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('mpesaTransaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plot.MpesaPayments')),
                ('plot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='plot.Plot')),
            ],
            options={
                'verbose_name_plural': 'Payment Details',
            },
        ),
    ]
