# Generated by Django 3.0.2 on 2020-12-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0005_landratespayments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plot',
            old_name='paind',
            new_name='paid',
        ),
    ]
